// Daily puzzles: counting. See types.ts for the rules every puzzle keeps.

import type {PuzzleCopy} from "@/lib/learn/copy/puzzles/types";

export const COMBINATORICS_PUZZLES: readonly PuzzleCopy[] = [
    {
        id: 'handshakes',
        title: 'Handshakes',
        category: 'combinatorics',
        difficulty: 1,
        prompt: ['Ten people meet, and every pair shakes hands exactly once.', 'How many handshakes are there?'],
        answer: '45',
        unit: 'handshakes',
        hints: ['Each handshake is a pair of people.', 'Each person shakes 9 hands, and every handshake has two people in it.'],
        solution: ['Ten people times 9 hands each counts every handshake twice.', 'So there are 10 × 9 / 2 = 45.'],
    },
    {
        id: 'grid-paths',
        title: 'Across a grid',
        category: 'combinatorics',
        difficulty: 1,
        prompt: [
            'On a square grid you walk from one corner to the opposite corner of a 4-by-4 block, moving only right or up along the lines.',
            'How many different shortest routes are there?',
        ],
        answer: '70',
        unit: 'routes',
        hints: ['Every shortest route is 8 steps: 4 rights and 4 ups.', 'A route is fixed by choosing which 4 of the 8 steps go right.'],
        solution: ['Choose the 4 right-steps among 8: C(8, 4).', 'That is 70 routes.'],
    },
    {
        id: 'committee-of-three',
        title: 'A committee of three',
        category: 'combinatorics',
        difficulty: 1,
        prompt: ['A committee of 3 people is chosen from a group of 8.', 'How many different committees are possible?'],
        answer: '56',
        unit: 'committees',
        hints: ['Order does not matter: the same three people are one committee.', 'Count ordered picks, then divide by the 3! orders of each committee.'],
        solution: ['Ordered picks: 8 × 7 × 6 = 336. Each committee appears in 3! = 6 orders.', 'So there are 336/6 = 56 committees, C(8, 3).'],
    },
    {
        id: 'level-anagrams',
        title: 'Rearranging LEVEL',
        category: 'combinatorics',
        difficulty: 1,
        prompt: ['How many different strings can be made by rearranging all five letters of the word LEVEL?'],
        answer: '30',
        unit: 'strings',
        hints: ['Five distinct letters would give 5! arrangements.', 'Swapping the two Ls, or the two Es, gives the same string.'],
        solution: ['5! = 120 counts each string 2! × 2! = 4 times.', 'So there are 120/4 = 30 different strings.'],
    },
    {
        id: 'full-houses',
        title: 'Full houses',
        category: 'combinatorics',
        difficulty: 2,
        prompt: ['A full house is five cards: three of one rank and two of another.', 'How many different full houses can be dealt from a standard 52-card deck?'],
        answer: '3744',
        unit: 'hands',
        hints: ['Pick the rank of the three, then which three suits; then the rank of the pair, then which two suits.', 'There are C(4, 3) = 4 ways to pick three suits and C(4, 2) = 6 ways to pick two.'],
        solution: ['13 ranks × 4 suit choices for the three, then 12 ranks × 6 suit choices for the pair.', '13 × 4 × 12 × 6 = 3,744 full houses.'],
    },
    {
        id: 'wrong-envelopes',
        title: 'Every letter misplaced',
        category: 'combinatorics',
        difficulty: 2,
        prompt: ['Four letters go into four addressed envelopes, one each.', 'In how many ways can every letter end up in a wrong envelope?'],
        answer: '9',
        unit: 'ways',
        hints: ['Letter 1 has three wrong envelopes to go to.', 'Say letter 1 goes to envelope 2: count the ways for letters 2, 3 and 4.'],
        solution: [
            'With letter 1 in envelope 2, letter 2 either goes to envelope 1 (one way for the other two) or not (two ways): three in all.',
            'Three choices for letter 1 times three gives 9 ways.',
        ],
    },
    {
        id: 'three-dice-ten',
        title: 'Three dice make ten',
        category: 'combinatorics',
        difficulty: 2,
        prompt: ['Three dice of different colours are rolled.', 'In how many of the 216 outcomes do they add up to 10?'],
        answer: '27',
        unit: 'outcomes',
        hints: ['Fix the first die and count the pairs for the other two.', 'Two dice make s in 6 − |s − 7| ways, for s from 2 to 12.'],
        solution: [
            'A first die of 1 to 6 leaves 9, 8, 7, 6, 5 and 4 for the other two: 4 + 5 + 6 + 5 + 4 + 3 ways.',
            'That is 27 outcomes.',
        ],
    },
    {
        id: 'coins-to-four',
        title: 'Ten coins, four people',
        category: 'combinatorics',
        difficulty: 2,
        prompt: ['Ten identical coins are shared among four people; some may get none.', 'In how many ways can that be done?'],
        answer: '286',
        unit: 'ways',
        hints: ['Lay the 10 coins in a row and drop in 3 dividers.', 'Each way is a choice of 3 positions for the dividers among 13 slots.'],
        solution: ['10 coins and 3 dividers fill 13 slots; choose where the dividers go.', 'C(13, 3) = 286 ways.'],
    },
    {
        id: 'round-table',
        title: 'A round table',
        category: 'combinatorics',
        difficulty: 1,
        prompt: [
            'Six people sit around a round table. Two seatings count as the same when everyone has the same left and right neighbours.',
            'How many different seatings are there?',
        ],
        answer: '120',
        unit: 'seatings',
        hints: ['Seat one person anywhere: the rest is measured from them.', 'The other five can be arranged in 5! ways.'],
        solution: ['Fix one person\'s seat; rotations then stop mattering.', 'The other five fill the remaining seats in 5! = 120 ways.'],
    },
    {
        id: 'no-neighbours',
        title: 'No two neighbours',
        category: 'combinatorics',
        difficulty: 3,
        prompt: [
            'How many subsets of the numbers 1 to 10 contain no two consecutive numbers? The empty set counts.',
        ],
        answer: '144',
        unit: 'subsets',
        hints: ['Let f(n) count the subsets of 1 to n. Either n is left out, or n is in and n − 1 is out.', 'So f(n) = f(n − 1) + f(n − 2), with f(1) = 2 and f(2) = 3.'],
        solution: ['The counts run 2, 3, 5, 8, 13, 21, 34, 55, 89, 144: Fibonacci numbers.', 'So f(10) = 144.'],
    },
];
