// Daily puzzles: estimation and mental arithmetic. See types.ts for the rules every puzzle keeps.
// An answer with a tolerance accepts anything within it; the prompt says how close is enough.

import type {PuzzleCopy} from "@/lib/learn/copy/puzzles/types";

export const ESTIMATION_PUZZLES: readonly PuzzleCopy[] = [
    {
        id: 'seconds-in-a-year',
        title: 'Seconds in a year',
        category: 'estimation',
        difficulty: 1,
        prompt: ['How many seconds are there in a 365-day year?', 'Within 1% is close enough.'],
        answer: '31536000',
        tolerance: 315360,
        unit: 'seconds',
        hints: ['A day has 24 × 60 × 60 = 86,400 seconds.', 'Multiply by 365.'],
        solution: ['86,400 × 365 = 31,536,000.', 'A handy memory: a year is about π × 10^7 seconds.'],
    },
    {
        id: 'doubling-time',
        title: 'Doubling at six percent',
        category: 'estimation',
        difficulty: 1,
        prompt: ['Money grows 6% a year, compounding once a year.', 'In about how many years does it double? Within half a year is close enough.'],
        answer: '11.9',
        tolerance: 0.5,
        unit: 'years',
        hints: ['The rule of 72: divide 72 by the rate in percent.', 'The exact figure is ln 2 / ln 1.06.'],
        solution: ['72 / 6 = 12 years by the rule of thumb.', 'Exactly, ln 2 / ln 1.06 ≈ 11.9 years.'],
    },
    {
        id: 'square-root-2000',
        title: 'The square root of 2000',
        category: 'estimation',
        difficulty: 2,
        prompt: ['Without a calculator, what is √2000 to one decimal place?'],
        answer: '44.7',
        tolerance: 0.05,
        hints: ['44² = 1936 and 45² = 2025.', 'Close to a square a², √(a² + d) ≈ a + d / (2a).'],
        solution: ['2000 is 64 above 44² = 1936, so √2000 ≈ 44 + 64/88 ≈ 44.73.', 'To one decimal: 44.7.'],
    },
    {
        id: 'ten-years-at-seven',
        title: 'Ten years at seven percent',
        category: 'estimation',
        difficulty: 2,
        prompt: ['$1,000 grows at 7% a year, compounding once a year, for 10 years.', 'What is it worth at the end, to the nearest dollar?'],
        answer: '1967.15',
        tolerance: 1,
        unit: 'dollars',
        hints: ['It is 1000 × 1.07^10.', 'By the rule of 72, 7% doubles money in about 10 years, so expect a little under $2,000.'],
        solution: ['1.07^10 ≈ 1.96715.', 'So $1,000 becomes about $1,967.15.'],
    },
    {
        id: 'compounding-limit',
        title: 'Compounding without end',
        category: 'estimation',
        difficulty: 2,
        prompt: [
            'A dollar earns 100% a year, compounded n times a year, so it ends the year at (1 + 1/n)^n.',
            'As n grows without limit, what does that approach? Three decimals is close enough.',
        ],
        answer: '2.718',
        tolerance: 0.002,
        unit: 'dollars',
        hints: ['n = 1 gives 2, n = 2 gives 2.25, n = 12 about 2.613.', 'The limit is a famous constant.'],
        solution: ['The values climb toward e, the base of natural logarithms.', 'e ≈ 2.718: continuous compounding at 100% for a year.'],
    },
    {
        id: 'digits-of-two-to-hundred',
        title: 'Digits of 2^100',
        category: 'estimation',
        difficulty: 2,
        prompt: ['How many digits does 2^100 have when written out in full?'],
        answer: '31',
        unit: 'digits',
        hints: ['2^10 = 1024 is a little over 10^3.', 'So 2^100 = (2^10)^10 is a little over 10^30.'],
        solution: ['2^100 = 1024^10 ≈ 1.27 × 10^30.', 'A number between 10^30 and 10^31 has 31 digits.'],
    },
    {
        id: 'random-walk-spread',
        title: 'A hundred coin-flip days',
        category: 'estimation',
        difficulty: 2,
        prompt: [
            'Each day a quantity moves up 1% or down 1% with equal probability, independently of other days.',
            'Adding up 100 days of moves, what is the standard deviation of the total, in percent?',
        ],
        answer: '10',
        unit: '%',
        hints: ['One day\'s move has variance 1 (in percent squared).', 'Variances of independent moves add.'],
        solution: ['100 independent days have variance 100 × 1 = 100.', 'The standard deviation is √100 = 10%: spread grows with the square root of time.'],
    },
    {
        id: 'down-twenty-up',
        title: 'Down twenty, then back',
        category: 'estimation',
        difficulty: 1,
        prompt: ['A price falls 20%.', 'By what percent must it then rise to return to where it started?'],
        answer: '25',
        unit: '%',
        hints: ['Start at 100: after the fall it is 80.', 'Going from 80 back to 100 is a rise of 20 on a base of 80.'],
        solution: ['80 × 1.25 = 100.', 'So it must rise 25%: a loss needs a larger gain to recover, because the gain starts from a smaller base.'],
    },
];
