// Daily puzzles: expected value. See types.ts for the rules every puzzle keeps.

import type {PuzzleCopy} from "@/lib/learn/copy/puzzles/types";

export const EXPECTED_VALUE_PUZZLES: readonly PuzzleCopy[] = [
    {
        id: 'one-die-payout',
        title: 'A fair price for a die',
        category: 'expected-value',
        difficulty: 1,
        prompt: ['A game pays you, in dollars, the number a fair die shows.', 'What price makes the game fair — its expected payout?'],
        answer: '7/2',
        unit: 'dollars',
        hints: ['Each face comes up with probability 1/6.', 'Add the six faces and divide by six.'],
        solution: ['(1 + 2 + 3 + 4 + 5 + 6)/6 = 21/6 = 3.5.', 'So $3.50 is the fair price.'],
    },
    {
        id: 'one-reroll',
        title: 'One reroll',
        category: 'expected-value',
        difficulty: 2,
        prompt: [
            'You roll a die and are paid its number in dollars. After seeing the first roll you may roll once more, but then you must take the second roll.',
            'Playing to make the expected payout as large as possible, what is it?',
        ],
        answer: '17/4',
        unit: 'dollars',
        hints: ['A second roll is worth 3.5 on average.', 'Keep the first roll exactly when it is above 3.5.'],
        solution: [
            'Keep a 4, 5 or 6 (average 5); reroll a 1, 2 or 3 and get 3.5 on average.',
            'Each case has probability 1/2, so the expected payout is (5 + 3.5)/2 = 4.25.',
        ],
    },
    {
        id: 'every-face',
        title: 'Every face once',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['A fair die is rolled until every one of its six faces has appeared at least once.', 'What is the expected number of rolls?'],
        answer: '147/10',
        unit: 'rolls',
        hints: [
            'Split the wait into stages: after k faces have appeared, a roll shows a new one with probability (6 − k)/6.',
            'A stage that succeeds with probability p takes 1/p rolls on average.',
        ],
        solution: [
            'The stages take 6/6, 6/5, 6/4, 6/3, 6/2 and 6/1 rolls on average.',
            'Their sum is 6 × (1 + 1/2 + 1/3 + 1/4 + 1/5 + 1/6) = 14.7 rolls.',
        ],
    },
    {
        id: 'first-six',
        title: 'Waiting for a six',
        category: 'expected-value',
        difficulty: 1,
        prompt: ['A fair die is rolled until it shows a six.', 'What is the expected number of rolls, counting the six?'],
        answer: '6',
        unit: 'rolls',
        hints: ['Each roll succeeds with probability 1/6, whatever came before.', 'A wait for a 1-in-p chance lasts p tries on average.'],
        solution: ['The number of rolls is geometric with success probability 1/6.', 'Its mean is 1/(1/6) = 6 rolls.'],
    },
    {
        id: 'heads-twice',
        title: 'Two heads in a row',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['A fair coin is flipped until two heads come up in a row.', 'What is the expected number of flips?'],
        answer: '6',
        unit: 'flips',
        hints: ['Let E be the expected flips from scratch and F the expected flips left just after a heads.', 'A tails always sends you back to scratch.'],
        solution: [
            'From scratch: E = 1 + E/2 + F/2. Just after a heads: F = 1 + E/2 (a tails restarts, a heads finishes).',
            'Solving the two gives F = 4 and E = 6 flips.',
        ],
    },
    {
        id: 'heads-then-tails',
        title: 'Heads, then tails',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['A fair coin is flipped until a heads is followed directly by a tails.', 'What is the expected number of flips?'],
        answer: '4',
        unit: 'flips',
        hints: ['Wait for the first heads, then wait for the first tails after it.', 'Once a heads has appeared, further heads change nothing.'],
        solution: [
            'The first heads takes 2 flips on average. After it, the first tails takes 2 more, and it always completes the pattern.',
            'So the wait is 2 + 2 = 4 flips — shorter than the 6 for heads-heads.',
        ],
    },
    {
        id: 'longer-piece',
        title: 'The longer piece',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['A stick one metre long is broken at a point chosen uniformly at random.', 'What is the expected length of the longer piece, in metres?'],
        answer: '3/4',
        unit: 'metres',
        hints: ['By symmetry, only a break in the left half needs working out.', 'With the break at x below 1/2, the longer piece is 1 − x.'],
        solution: ['For a break uniform on [0, 1/2], the longer piece 1 − x is uniform on [1/2, 1].', 'Its average is 3/4 of a metre.'],
    },
    {
        id: 'higher-of-two-dice',
        title: 'The higher of two dice',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['Two fair dice are rolled.', 'What is the expected value of the higher of the two numbers?'],
        answer: '161/36',
        hints: ['The higher die is k when both are at most k but not both at most k − 1.', 'So P(max = k) = (k² − (k − 1)²)/36 = (2k − 1)/36.'],
        solution: [
            'Sum k × (2k − 1)/36 over k = 1 … 6: (1 + 6 + 15 + 28 + 45 + 66)/36.',
            'That is 161/36, about 4.47.',
        ],
    },
    {
        id: 'larger-of-two-uniforms',
        title: 'The larger of two numbers',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['Two numbers are drawn independently and uniformly between 0 and 1.', 'What is the expected value of the larger one?'],
        answer: '2/3',
        hints: ['Two random points split [0, 1] into three pieces.', 'By symmetry, the three pieces have the same expected length.'],
        solution: [
            'The two points cut the interval into three pieces, each 1/3 long on average.',
            'The larger point sits after two of those pieces, so its expected value is 2/3.',
        ],
    },
    {
        id: 'square-of-a-die',
        title: 'Paid the square',
        category: 'expected-value',
        difficulty: 1,
        prompt: ['A game pays you the square of a fair die\'s number, in dollars: 1, 4, 9, 16, 25 or 36.', 'What is the expected payout?'],
        answer: '91/6',
        unit: 'dollars',
        hints: ['Add the six squares.', 'Then divide by six.'],
        solution: ['1 + 4 + 9 + 16 + 25 + 36 = 91.', 'So the expected payout is 91/6, about $15.17 — more than 3.5², because squaring stretches the high rolls.'],
    },
    {
        id: 'cards-to-first-ace',
        title: 'Cards to the first ace',
        category: 'expected-value',
        difficulty: 3,
        prompt: [
            'A shuffled 52-card deck is dealt one card at a time until the first ace appears.',
            'What is the expected number of cards dealt, counting the ace?',
        ],
        answer: '53/5',
        unit: 'cards',
        hints: ['The four aces split the 48 other cards into five gaps.', 'By symmetry each gap holds the same number of cards on average.'],
        solution: [
            'The 48 non-aces fall into five gaps around the aces, 48/5 = 9.6 cards each on average.',
            'The first ace comes after the first gap, so the expected count is 9.6 + 1 = 10.6 cards.',
        ],
    },
    {
        id: 'own-hats',
        title: 'Hats in a pile',
        category: 'expected-value',
        difficulty: 2,
        prompt: ['Ten people throw their hats into a pile, and each takes one back at random.', 'What is the expected number of people who get their own hat?'],
        answer: '1',
        unit: 'people',
        hints: ['Ask what the chance is that one particular person gets their own hat.', 'Expectations add up even when the events depend on each other.'],
        solution: [
            'Each person gets their own hat with probability 1/10.',
            'Adding over the ten people gives an expected 10 × 1/10 = 1, whatever the number of people.',
        ],
    },
];
