// Daily puzzles: logic. See types.ts for the rules every puzzle keeps.

import type {PuzzleCopy} from "@/lib/learn/copy/puzzles/types";

export const LOGIC_PUZZLES: readonly PuzzleCopy[] = [
    {
        id: 'hundred-lockers',
        title: 'A hundred lockers',
        category: 'logic',
        difficulty: 2,
        prompt: [
            'A hallway has 100 closed lockers. Student 1 opens every locker; student 2 toggles every 2nd; student 3 every 3rd; and so on up to student 100.',
            'How many lockers are open at the end?',
        ],
        answer: '10',
        unit: 'lockers',
        hints: ['Locker n is toggled once for each of its divisors.', 'It ends open when it was toggled an odd number of times.'],
        solution: [
            'Divisors come in pairs (d and n/d), except when n is a perfect square, which has an odd number of divisors.',
            'So the open lockers are 1, 4, 9 … 100: ten of them.',
        ],
    },
    {
        id: 'bat-and-ball',
        title: 'A bat and a ball',
        category: 'logic',
        difficulty: 1,
        prompt: ['A bat and a ball cost $1.10 together. The bat costs $1.00 more than the ball.', 'How much does the ball cost, in cents?'],
        answer: '5',
        unit: 'cents',
        hints: ['If the ball cost 10 cents, the bat would cost $1.10, and the pair $1.20.', 'Write the ball as x: x + (x + 1.00) = 1.10.'],
        solution: ['2x + 1.00 = 1.10, so x = 0.05.', 'The ball costs 5 cents and the bat $1.05.'],
    },
    {
        id: 'lily-pads',
        title: 'Lily pads',
        category: 'logic',
        difficulty: 1,
        prompt: ['A patch of lily pads doubles in size every day. It covers the whole lake on day 48.', 'On which day did it cover half the lake?'],
        answer: '47',
        unit: 'day',
        hints: ['Work backwards one day from a full lake.', 'Doubling half a lake fills it.'],
        solution: ['The patch doubles overnight, so the day before it covered the lake it covered half.', 'That is day 47.'],
    },
    {
        id: 'widget-machines',
        title: 'Machines and widgets',
        category: 'logic',
        difficulty: 1,
        prompt: ['5 machines make 5 widgets in 5 minutes.', 'How many minutes do 100 machines take to make 100 widgets?'],
        answer: '5',
        unit: 'minutes',
        hints: ['How long does one machine take to make one widget?', 'The machines work at the same time.'],
        solution: ['Each machine makes one widget in 5 minutes.', '100 machines working side by side make 100 widgets in the same 5 minutes.'],
    },
    {
        id: 'heavier-coin',
        title: 'The heavier coin',
        category: 'logic',
        difficulty: 2,
        prompt: [
            'Nine coins look alike, but one is slightly heavier. You have a balance scale and no weights.',
            'What is the smallest number of weighings that always finds the heavy coin?',
        ],
        answer: '2',
        unit: 'weighings',
        hints: ['A weighing has three outcomes: left heavier, right heavier, or level.', 'Weigh three coins against three.'],
        solution: [
            'Three against three either finds the heavier group or shows it is the three left out. One more weighing of one coin against one picks it out the same way.',
            'One weighing can only split nine coins three ways, so it cannot always find the coin: the answer is 2.',
        ],
    },
    {
        id: 'clock-hands',
        title: 'Hands together',
        category: 'logic',
        difficulty: 2,
        prompt: ['In one full day, from midnight to the next midnight, how many times do the hour and minute hands of a clock point the same way?', 'Count midnight once.'],
        answer: '22',
        unit: 'times',
        hints: ['The minute hand gains one full lap on the hour hand between meetings.', 'In 12 hours the minute hand makes 12 laps and the hour hand 1.'],
        solution: [
            'The minute hand laps the hour hand 11 times every 12 hours, so the hands meet every 12/11 hours.',
            'In 24 hours that is 22 meetings, counting the one at midnight once.',
        ],
    },
    {
        id: 'trailing-zeros',
        title: 'Zeros at the end',
        category: 'logic',
        difficulty: 2,
        prompt: ['100! is 1 × 2 × 3 × … × 100.', 'How many zeros does it end with?'],
        answer: '24',
        unit: 'zeros',
        hints: ['Each trailing zero needs a factor of 10 = 2 × 5, and twos are far more common than fives.', 'Count the multiples of 5, then the extra five in each multiple of 25.'],
        solution: ['There are 20 multiples of 5 up to 100, and 4 of them (25, 50, 75, 100) carry a second five.', 'That is 24 fives, so 24 trailing zeros.'],
    },
    {
        id: 'snail-on-a-wall',
        title: 'A snail on a wall',
        category: 'logic',
        difficulty: 1,
        prompt: ['A snail at the foot of a 10 m wall climbs 3 m each day and slips back 2 m each night.', 'On which day does it reach the top?'],
        answer: '8',
        unit: 'day',
        hints: ['It gains 1 m per full day and night — until the day it gets there.', 'Once it reaches the top during a day, the night does not count.'],
        solution: ['After 7 days and nights it is 7 m up.', 'On day 8 it climbs 3 m to 10 m and is at the top.'],
    },
    {
        id: 'four-cards-rule',
        title: 'Four cards and a rule',
        category: 'logic',
        difficulty: 2,
        prompt: [
            'Each card has a letter on one side and a number on the other. On the table you see A, K, 4 and 7.',
            'Rule: a card with a vowel on one side has an even number on the other. What is the smallest number of cards you must turn over to check the rule?',
        ],
        answer: '2',
        unit: 'cards',
        hints: ['A card matters only if its hidden side could break the rule.', 'An even number may have anything behind it; an odd one may not hide a vowel.'],
        solution: [
            'Turn the A (it needs an even number behind it) and the 7 (it must not hide a vowel).',
            'The K and the 4 cannot break the rule whatever is behind them, so the answer is 2.',
        ],
    },
    {
        id: 'fly-between-trains',
        title: 'A fly between trains',
        category: 'logic',
        difficulty: 1,
        prompt: [
            'Two trains 100 miles apart head toward each other at 50 mph each. A fly flies back and forth between them at 75 mph until they meet.',
            'How many miles does the fly travel?',
        ],
        answer: '75',
        unit: 'miles',
        hints: ['There is no need to add up the zigzags.', 'How long until the trains meet?'],
        solution: ['The trains close at 100 mph, so they meet after one hour.', 'Flying at 75 mph for one hour, the fly covers 75 miles.'],
    },
];
