// The preflop table: each starting-hand class's exact all-in equity against each other class, read
// from lib/poker/data/preflop-equity.json (generated by scripts/poker-preflop-equity.mjs, never
// edited by hand), and how many disjoint combo pairs each pair of classes has — the card removal a
// class-level calculation weighs by. Pure.

import {CLASS_COMBOS, CLASSES, COMBO_HI, COMBO_LO} from "@/lib/poker/cards";

export type PreflopFile = {format: number; scale: number; classes: number; upper: readonly number[]};

export type PreflopTable = {
    // Class i's equity against class j: the stored upper triangle, 1 − it below, ½ on the diagonal.
    equity: (i: number, j: number) => number;
    // pairs[i * 169 + j]: combo pairs (one of i, one of j) that share no card.
    pairs: Float64Array;
    // Each class's equity against a random hand, weighed by card removal.
    vsRandom: Float64Array;
};

const upperIndex = (i: number, j: number) => i * CLASSES - (i * (i + 1)) / 2 + (j - i - 1);

// Disjoint combo pairs between every two classes: about a millisecond's work, done once.
export const pairCounts = (): Float64Array => {
    const out = new Float64Array(CLASSES * CLASSES);
    for (let i = 0; i < CLASSES; i++) {
        for (let j = 0; j < CLASSES; j++) {
            let n = 0;
            for (const a of CLASS_COMBOS[i]) for (const b of CLASS_COMBOS[j]) {
                if (COMBO_HI[a] !== COMBO_HI[b] && COMBO_HI[a] !== COMBO_LO[b] && COMBO_LO[a] !== COMBO_HI[b] && COMBO_LO[a] !== COMBO_LO[b]) n++;
            }
            out[i * CLASSES + j] = n;
        }
    }
    return out;
};

export const decodePreflop = (file: PreflopFile): PreflopTable => {
    if (file.format !== 1 || file.classes !== CLASSES || file.upper.length !== (CLASSES * (CLASSES - 1)) / 2) {
        throw new Error('preflop table: unexpected shape');
    }
    const scale = file.scale;
    const equity = (i: number, j: number): number =>
        i === j ? 0.5 : i < j ? file.upper[upperIndex(i, j)] / scale : 1 - file.upper[upperIndex(j, i)] / scale;
    const pairs = pairCounts();
    const vsRandom = new Float64Array(CLASSES);
    for (let i = 0; i < CLASSES; i++) {
        let num = 0;
        let den = 0;
        for (let j = 0; j < CLASSES; j++) {
            const n = pairs[i * CLASSES + j];
            num += n * equity(i, j);
            den += n;
        }
        vsRandom[i] = num / den;
    }
    return {equity, pairs, vsRandom};
};

// The 169 classes from the highest equity against a random hand to the lowest: the range editor's
// "top x%".
export const rankingOf = (table: PreflopTable): number[] =>
    Array.from({length: CLASSES}, (_, id) => id).sort((x, y) => table.vsRandom[y] - table.vsRandom[x] || x - y);
